# ############################################################################
# Model: Joint E2E Model for ASR and Dependency Parsing
# Encoder: wav2vec2
# Tokens: BPE
# losses: CTC
# Training Data: SWBD
# Authors:  Shunsuke Kando
# ############################################################################
# Seed needs to be set at top of yaml, before objects with parameters are made

dataset: en-swbd # NOTE: if you run on orfeo, specify `fr-orfeo` on command-line
seed: 1234
__set_seed: !!python/object/apply:torch.manual_seed [!ref <seed>]
output_folder: !ref results/wav2vec2ctc/<dataset>/<seed>
wer_file: !ref <output_folder>/wer.tx
save_folder: !ref <output_folder>/save
hf_cache: !ref <save_folder>/wav2vec2_checkpoint
train_log: !ref <output_folder>/train_log.txt

# Data files
data_folder: /path/to/data_folder # Specify on command-line
train_csv: !ref <data_folder>/train.csv
valid_csv: !ref <data_folder>/dev.csv
test_csv: !ref <data_folder>/test.csv

#CONLLU GOLD FILE used for evaluation
dev_gold_conllu: !ref <data_folder>/dev.conllu
test_gold_conllu: !ref <data_folder>/test.conllu
dev_output_conllu: !ref <output_folder>/dev_predicted.conllu
test_output_conllu: !ref <output_folder>/test_predicted.conllu
transcript_file: transcript_test_AUDIO

# pre-trained model
wav2vec2_hub: facebook/wav2vec2-large-robust # NOTE: if you run on orfeo, specify `LeBenchmark/wav2vec2-FR-7K-large` on command-line

# We remove utterance slonger than 10s in the train/dev/test sets as
# longer sentences certainly correspond to "open microphones".
avoid_if_longer_than: 10.0

# Training parameters
number_of_epochs: 30
lr: 1.0
lr_wav2vec: 0.0001
auto_mix_prec: False
sample_rate: 16000
sorting: ascending
ckpt_interval_minutes: 30 # save checkpoint every N min

# With data_parallel batch_size is split into N jobs
# With DDP batch_size is multiplied by N jobs
# Must be 6 per GPU to fit 16GB of VRAM
batch_size: 12
test_batch_size: 4

dataloader_options:
    batch_size: !ref <batch_size>
    num_workers: 6
    shuffle: False
test_dataloader_options:
    batch_size: !ref <test_batch_size>
    num_workers: 6

# BPE parameters
token_type: bpe  # ["unigram", "bpe", "char"]
character_coverage: 1.0

# Model parameters
dnn_activation: !new:torch.nn.LeakyReLU
dnn_dropout: 0.15
dnn_neurons: 1024
freeze_wav2vec: False

# Outputs
output_neurons: 1000  # BPE size

# Decoding parameters
# Be sure that the bos and eos index match with the BPEs ones
blank_index: 0
bos_index: 1
eos_index: 2
min_decode_ratio: 0.0
max_decode_ratio: 1.0
beam_size: 80
eos_threshold: 1.5
using_max_attn_shift: True
max_attn_shift: 140
ctc_weight_decode: 0.0
temperature: 1.50

#
#
#


#
# Functions and classes
#
epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

augmentation: !new:speechbrain.lobes.augment.TimeDomainSpecAugment
    sample_rate: !ref <sample_rate>
    speeds: [95, 100, 105]

enc: !new:speechbrain.nnet.containers.Sequential
    input_shape: [null, null, 1024]
    linear1: !name:speechbrain.nnet.linear.Linear
        n_neurons: !ref <dnn_neurons>
        bias: True
    bn1: !name:speechbrain.nnet.normalization.LayerNorm
    activation: !ref <dnn_activation>
    drop: !new:torch.nn.Dropout
        p: !ref <dnn_dropout>
    linear2: !name:speechbrain.nnet.linear.Linear
        n_neurons: !ref <dnn_neurons>
        bias: True
    bn2: !name:speechbrain.nnet.normalization.LayerNorm
    activation2: !ref <dnn_activation>
    drop2: !new:torch.nn.Dropout
        p: !ref <dnn_dropout>
    linear3: !name:speechbrain.nnet.linear.Linear
        n_neurons: !ref <dnn_neurons>
        bias: True
    bn3: !name:speechbrain.nnet.normalization.LayerNorm
    activation3: !ref <dnn_activation>

wav2vec2: !new:speechbrain.lobes.models.huggingface_wav2vec.HuggingFaceWav2Vec2
    source: !ref <wav2vec2_hub>
    output_norm: True
    freeze: !ref <freeze_wav2vec>
    save_path: !ref <hf_cache>

ctc_lin: !new:speechbrain.nnet.linear.Linear
    input_size: !ref <dnn_neurons>
    n_neurons: !ref <output_neurons>

log_softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True


# Loss functions

ctc_cost: !name:speechbrain.nnet.losses.ctc_loss
    blank_index: !ref <blank_index>


# Modules and training model parameter

modules:
    wav2vec2: !ref <wav2vec2>
    enc: !ref <enc>
    ctc_lin: !ref <ctc_lin>


model: !new:torch.nn.ModuleList
    - [!ref <enc>, !ref <ctc_lin>]

model_opt_class: !name:torch.optim.Adadelta
    lr: !ref <lr>
    rho: 0.95
    eps: 1.e-8

wav2vec_opt_class: !name:torch.optim.Adam
    lr: !ref <lr_wav2vec>

lr_annealing_model: !new:speechbrain.nnet.schedulers.NewBobScheduler
    initial_value: !ref <lr>
    improvement_threshold: 0.0025
    annealing_factor: 0.5
    patient: 0

lr_annealing_wav2vec: !new:speechbrain.nnet.schedulers.NewBobScheduler
    initial_value: !ref <lr_wav2vec>
    improvement_threshold: 0.0025
    annealing_factor: 0.7
    patient: 0

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        wav2vec2: !ref <wav2vec2>
        model: !ref <model>
        scheduler_model: !ref <lr_annealing_model>
        scheduler_wav2vec: !ref <lr_annealing_wav2vec>
        counter: !ref <epoch_counter>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>

#train_logger: !new:speechbrain.utils.train_logger.WandBLogger
#        yaml_config: hparams/logger.yaml

#
# METRICS
#
error_rate_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats

cer_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats
    split_tokens: True
